<a href="https://colab.research.google.com/github/hj151mids/rnn/blob/main/IDS703hw8%20Recurrent%20Neural%20network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

#from gen_gbu import gen_gbu


def prepare_data(X, Y):
    vocabulary = sorted(set([word for sequence in X for word in sequence]))
    one_hot_len = len(vocabulary)
    one_hot_vectors = dict()
    for i in range(one_hot_len):
        one_hot_vector = [0 for _ in range(one_hot_len)]
        one_hot_vector[i] = 1
        one_hot_vectors[vocabulary[i]] = one_hot_vector
    X = [
        torch.Tensor([
            one_hot_vectors[word]
            for word in sequence
        ])
        for sequence in X
    ]
    Y = torch.Tensor(Y)
    return X, Y


class LinearActivation(nn.Module):
    def forward(self, input: torch.Tensor) -> torch.Tensor:
        return input
'''
class Sum(nn.Module):
    def forward(self, input: torch.Tensor) -> torch.Tensor:
        return torch.sum(input)

class FirstLayer(nn.Module):
  def __init__(self, size_in, size_out, bias = False):
    super().__init__()
    self.input_size = size_in
    self.output_size = size_out
    weights = torch.Tensor([np.log(1), np.log(2), np.log(3), np.log(4), np.log(5)])
    self.weights = nn.Parameter(weights)
    # self.out_features = # weight init
    fan_in, _ = nn.init._calculate_fan_in_and_fan_out(self.weights)

  def forward(self, input, output_size):
    weight_times_input= input * self.weights
    return weight_times_input
'''
class MyRNN(nn.Module):
    """Simple RNN."""
    def __init__(self, input_size, message_size, output_size=1, **kwargs):
        """Initialize."""
        super().__init__(**kwargs)

        """
        self.to_message = nn.Sequential(
            #nn.Linear(input_size + message_size, message_size, bias=False),
            FirstLayer(input_size, output_size, bias = False),
            expActivation(),
        )
        self.to_output = nn.Sequential(
            #nn.Linear(input_size + message_size, output_size, bias=False),
            FirstLayer(input_size, output_size, bias = False),
            expActivation(),
        )
        # self.to_message.weight.data = torch.Tensor([[-1, 1, 0, 1]])
        """
        #only a linear layer is enough
        self.to_message = nn.Sequential(
            nn.Linear(input_size + message_size, message_size, bias=False),
            LinearActivation(),
        )
        #self.to_message.weight.data = torch.Tensor([[0, 0.7, 1.1, 1.4, 1.6]])
        #We just have one linear neuron so we don't need this sequence
        #The provided code is for two linear neurons. 
        #self.to_output = nn.Sequential(
            #nn.Linear(input_size + message_size, output_size, bias=False),
            #LinearActivation(),
        #)

        #print(torch.exp(self.to_output[0]))

    def forward(self, sequence):
        """Run forward."""
        message = torch.zeros(self.to_message[0].out_features)
        #print(self.to_message[0].out_features)
        outputs = []
        for token in sequence: # combine inputs + message
            _in = torch.cat((token, message), axis=0)
            message = self.to_message(_in)
            #output takes the exponential of the message
            #I don't need to have an individual layer of exp
            outputs.append(torch.exp(message))
        return message, outputs

def main():
    """Run experiment."""
    N = 200
    X_train, Y_train = gen_gbu(N)
    X_train, Y_train = prepare_data(X_train, Y_train)

    # initialize the network
    message_size = 1
    input_size = len(X_train[0][0])
    net = MyRNN(input_size, message_size, 1)

    # Create loss function and specify optimizer
    criterion = nn.MSELoss(reduction="sum")
    LR = 0.01
    optimizer = optim.Adam(net.parameters(), lr=LR, betas=(0.9, 0.99))

    # train the model
    for i in range(200):
        net.train()
        optimizer.zero_grad()
        #should also take out the output
        for sequence, label in zip(X_train, Y_train):
            message, output = net(sequence)
            #I should use the output to compare with the label, not the message
            #since the message is not what we want here because message is accumulative multiplication
            #not our desired output
            loss = criterion(output[-1], label)
            loss.backward()
        optimizer.step()

        net.eval()
        with torch.no_grad():
            loss_total = 0
            for sequence, label in zip(X_train, Y_train):
                #change it here
                message, output = net(sequence)
                print(torch.exp(message))
                loss = criterion(output[-1], label)
                loss_total += loss.item()
        print("epoch", i)
        print("### loss: {}".format(loss_total/N))
    print(net.to_message[0].weight)


if __name__ == "__main__":
    main()


/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py:528: UserWarning: Using a target size (torch.Size([])) that is different to the input size (torch.Size([1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


Streaming output truncated to the last 5000 lines.
tensor([172121.5000])
tensor([10047584.])
tensor([186133.0938])
tensor([9850.2344])
tensor([7171281.5000])
tensor([13555.2637])
tensor([8.7918e+08])
tensor([14817510.])
tensor([2419921.])
tensor([255313.0781])
tensor([80215384.])
tensor([60892.9922])
tensor([4019848.])
tensor([355954.9375])
tensor([204512.8125])
tensor([6435.1060])
tensor([7898.0557])
tensor([515289.8750])
tensor([3005732.5000])
tensor([3442.1721])
tensor([1152.8430])
tensor([945426.8125])
tensor([38005.1484])
tensor([5884315.5000])
tensor([2903448.2500])
tensor([225680.7500])
tensor([3525224.5000])
tensor([2550885.7500])
tensor([4927748.5000])
tensor([199748.6094])
tensor([1454445.1250])
tensor([816602.2500])
tensor([1995153.])
tensor([831.2515])
tensor([4901782.])
tensor([4317.7104])
tensor([1152.8430])
tensor([50052852.])
tensor([120036.8203])
tensor([42472256.])
tensor([291636.5000])
tensor([4246.8521])
tensor([17123.5664])
tensor([41490444.])
tensor([4352448.5000]

In [ ]:
"""Generate sentiment analysis data."""
import numpy as np

VOCAB = ["one", "two", "three", "four", "five"]


def gen_gbu(nobs=10000):
    """Generate good/bad/uh data."""
    data = []
    product = []
    for _ in range(nobs):
        num_positions = np.random.randint(5, 20)
        words = np.random.choice(
            VOCAB,
            num_positions,
            p=np.random.dirichlet([0.2, 0.2, 0.2, 0.2, 0.2])
        )

        counter = 1
        for word in words:
          if word == "one":
            counter = counter*1
          elif word == "two":
            counter = counter*2
          elif word == "three":
            counter = counter*3
          elif word == "four":
            counter = counter*4
          else:
            counter = counter*5
        product.append(counter)
        data.append(list(words))
    return data, product


def main():
    """Test GBU data."""
    X, Y = gen_gbu()
    print(X)
    print(Y)


if __name__ == "__main__":
    main()
#more data here, more iterations to get more accurate results
#change the learning rate if the loss is getting larger, change to a lower 1
#everytime multiply by 0.1

[['five', 'four', 'four', 'four', 'five', 'five', 'five', 'one'], ['five', 'four', 'four', 'five', 'five', 'five', 'five', 'five', 'five'], ['four', 'four', 'one', 'four', 'two', 'one', 'two', 'one', 'four', 'one', 'two'], ['three', 'three', 'three', 'three', 'three', 'three', 'three', 'three', 'three', 'three'], ['four', 'four', 'five', 'four', 'four', 'four', 'four', 'two', 'four', 'two', 'four', 'three', 'five', 'two'], ['five', 'five', 'five', 'five', 'five', 'five'], ['two', 'two', 'five', 'two', 'five', 'two', 'five', 'one', 'five', 'two'], ['five', 'two', 'two', 'one', 'five', 'five', 'two', 'two', 'five', 'two', 'two', 'five', 'two', 'two', 'five', 'five', 'five'], ['five', 'five', 'five', 'five', 'three', 'five', 'three', 'five', 'five', 'five', 'five', 'five', 'two', 'five', 'five'], ['four', 'four', 'four', 'four', 'four', 'four', 'four', 'four', 'four'], ['four', 'four', 'four', 'four', 'four', 'four', 'four', 'four', 'four', 'four', 'four', 'four'], ['one', 'one', 'four', 